# Generated by Django 3.1.7 on 2021-03-21 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=50)),
                ('date_of_pub', models.DateTimeField(default=datetime.datetime(2021, 3, 21, 5, 27, 25, 721297), verbose_name='Date/Time')),
            ],
        ),
    ]
