# Generated by Django 3.1.7 on 2021-03-21 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210321_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_of_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 5, 46, 17, 14110), verbose_name='Date/Time'),
        ),
    ]
