# Generated by Django 3.1.7 on 2021-03-21 07:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210321_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_of_pub',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 13, 1, 51, 383983), verbose_name='Date/Time'),
        ),
    ]
