# Generated by Django 3.1.7 on 2021-03-26 05:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=50)),
                ('task_desc', models.TextField(blank=True)),
                ('date_of_pub', models.DateTimeField(default=datetime.datetime(2021, 3, 26, 5, 19, 16, 434029, tzinfo=utc), verbose_name='Date/Time')),
                ('user', models.ForeignKey(default='Guest', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
